### ISSUE TITLE
how to install the script

### ISSUE THREAD

**Issue by SangHLee** [xr09/cron-last-sunday#1]
Just wondering whether I need additional packages to install the program. I am using Ubuntu 14.04 LTS and have followed the instruction to install the script, but I am trouble using the script...

**Comment by xr09** [comment]
Just copy the script to a global path on your system: `cp -av run-if-today /usr/local/bin/` should work.

Then edit you crontab with: `crontab -e` and use the full path:

`30 6 * * 6 root  /usr/local/bin/run-if-today 1 Sat && /root/myscript.sh`

**Comment by SangHLee** [comment]
Thanks for the reply! 

Do I need to install root-system-bin to run run-if-today? You use "root" in your full path in crontab -e.

**Comment by SangHLee** [comment]
Never mind. I just copied the script to some other directory and it worked! Thanks!
